Fix HEIF plugin build (version check)
This build failure happens if you have libheif 1.10.0 installed:

plugins/impex/heif/HeifExport.cpp:461:21: error: no member named
'macOS_compatibility_workaround_no_nclx_profile' in
'heif::Context::EncodingOptions'
            options.macOS_compatibility_workaround_no_nclx_profile = false;

That option was added to libheif just **after** the 1.10.0 release.
Bump the version requirement to avoid the build-failure (which affects
people trying to build Krita 5.0 on FreeBSD).